### ISSUE TITLE
Deleting original image

### ISSUE THREAD

**Issue by law12019** [girder/large_image#245] opened 2018-01-15 18:10 UTC
To reproduce the problem:

1: upload and image
2: Enable large image on the item
3: Copy the item
4: Delete the original item
5: Copy the copied item

Thumbnail does not show up

6: Open the new copy

Image does not display

Console reports these error messages:

macro:1 GET http://images.slide-atlas.org/api/v1/item/5a5ce2f61fbb9005313792cb/tiles/images/macro?width=160&height=100 500 (Internal Server Error)
Image (async)
attr @ girder_lib.min.js:1
Be @ girder_lib.min.js:1
attr @ girder_lib.min.js:1
(anonymous) @ plugin.min.js:1
each @ girder_lib.min.js:1
each @ girder_lib.min.js:1
i @ plugin.min.js:1
(anonymous) @ plugin.min.js:1
r @ girder_lib.min.js:1
dispatch @ girder_lib.min.js:1
m.handle @ girder_lib.min.js:1
/api/v1/item/5a5ce2f61fbb9005313792cb/tiles/thumbnail?width=160&height=100:1 GET http://images.slide-atlas.org/api/v1/item/5a5ce2f61fbb9005313792cb/tiles/thumbnail?width=160&height=100 500 (Internal Server Error)
Image (async)
attr @ girder_lib.min.js:1
Be @ girder_lib.min.js:1
attr @ girder_lib.min.js:1
(anonymous) @ plugin.min.js:1
each @ girder_lib.min.js:1
each @ girder_lib.min.js:1
i @ plugin.min.js:1
(anonymous) @ plugin.min.js:1
r @ girder_lib.min.js:1
dispatch @ girder_lib.min.js:1
m.handle @ girder_lib.min.js:1
label:1 GET http://images.slide-atlas.org/api/v1/item/5a5ce2f61fbb9005313792cb/tiles/images/label?width=160&height=100 500 (Internal Server Error)
Image (async)
attr @ girder_lib.min.js:1
Be @ girder_lib.min.js:1
attr @ girder_lib.min.js:1
(anonymous) @ plugin.min.js:1
each @ girder_lib.min.js:1
each @ girder_lib.min.js:1
i @ plugin.min.js:1
(anonymous) @ plugin.min.js:1
r @ girder_lib.min.js:1
dispatch @ girder_lib.min.js:1
m.handle @ girder_lib.min.js:1
macro:1 GET http://images.slide-atlas.org/api/v1/item/5a5cdf401fbb900531e4e1df/tiles/images/macro?width=160&height=100 500 (Internal Server Error)
Image (async)
attr @ girder_lib.min.js:1
Be @ girder_lib.min.js:1
attr @ girder_lib.min.js:1
(anonymous) @ plugin.min.js:1
each @ girder_lib.min.js:1
each @ girder_lib.min.js:1
i @ plugin.min.js:1
(anonymous) @ plugin.min.js:1
r @ girder_lib.min.js:1
dispatch @ girder_lib.min.js:1
m.handle @ girder_lib.min.js:1
thumbnail:1 GET http://images.slide-atlas.org/api/v1/item/5a5cdf401fbb900531e4e1df/tiles/thumbnail?width=160&height=100 500 (Internal Server Error)
Image (async)
attr @ girder_lib.min.js:1
Be @ girder_lib.min.js:1
attr @ girder_lib.min.js:1
(anonymous) @ plugin.min.js:1
each @ girder_lib.min.js:1
each @ girder_lib.min.js:1
i @ plugin.min.js:1
(anonymous) @ plugin.min.js:1
r @ girder_lib.min.js:1
dispatch @ girder_lib.min.js:1
m.handle @ girder_lib.min.js:1
label:1 GET http://images.slide-atlas.org/api/v1/item/5a5cdf401fbb900531e4e1df/tiles/images/label?width=160&height=100 500 (Internal Server Error)
Image (async)
attr @ girder_lib.min.js:1
Be @ girder_lib.min.js:1
attr @ girder_lib.min.js:1
(anonymous) @ plugin.min.js:1
each @ girder_lib.min.js:1
each @ girder_lib.min.js:1
i @ plugin.min.js:1
(anonymous) @ plugin.min.js:1
r @ girder_lib.min.js:1
dispatch @ girder_lib.min.js:1
m.handle @ girder_lib.min.js:1
VM254:1 GET http://images.slide-atlas.org/api/v1/item/5a5ce2f61fbb9005313792cb/tiles 500 (Internal Server Error)
(anonymous) @ VM254:1
send @ girder_lib.min.js:1
ajax @ girder_lib.min.js:1
S @ girder_lib.min.js:1
initialize @ plugin.min.js:1
initialize @ plugin.min.js:1
t.View @ girder_lib.min.js:1
constructor @ girder_lib.min.js:1
O.n @ girder_lib.min.js:1
O.n @ girder_lib.min.js:1
_selectViewer @ plugin.min.js:1
render @ plugin.min.js:1
(anonymous) @ plugin.min.js:1
getSettings @ plugin.min.js:1
initialize @ plugin.min.js:1
t.View @ girder_lib.min.js:1
constructor @ girder_lib.min.js:1
O.n @ girder_lib.min.js:1
(anonymous) @ plugin.min.js:1
(anonymous) @ girder_lib.min.js:1
(anonymous) @ girder_lib.min.js:1
y @ girder_lib.min.js:1
v @ girder_lib.min.js:1
u @ girder_lib.min.js:1
d.trigger @ girder_lib.min.js:1
(anonymous) @ girder_lib.min.js:1
(anonymous) @ girder_lib.min.js:1
(anonymous) @ girder_lib.min.js:1
y @ girder_lib.min.js:1
v @ girder_lib.min.js:1
u @ girder_lib.min.js:1
d.trigger @ girder_lib.min.js:1
(anonymous) @ girder_lib.min.js:1
y @ girder_lib.min.js:1
v @ girder_lib.min.js:1
u @ girder_lib.min.js:1
d.trigger @ girder_lib.min.js:1
(anonymous) @ girder_lib.min.js:1
c @ girder_lib.min.js:1
d @ girder_lib.min.js:1
setTimeout (async)
(anonymous) @ girder_lib.min.js:1
l @ girder_lib.min.js:1
fireWith @ girder_lib.min.js:1
fire @ girder_lib.min.js:1
l @ girder_lib.min.js:1
fireWith @ girder_lib.min.js:1
n @ girder_lib.min.js:1
(anonymous) @ girder_lib.min.js:1
XMLHttpRequest.send (async)
(anonymous) @ VM254:1
send @ girder_lib.min.js:1
ajax @ girder_lib.min.js:1
S @ girder_lib.min.js:1
i @ girder_lib.min.js:1
fetch @ girder_lib.min.js:1
initialize @ girder_lib.min.js:1
t.View @ girder_lib.min.js:1
constructor @ girder_lib.min.js:1
O.n @ girder_lib.min.js:1
(anonymous) @ girder_lib.min.js:1
(anonymous) @ girder_lib.min.js:1
(anonymous) @ girder_lib.min.js:1
(anonymous) @ girder_lib.min.js:1
y @ girder_lib.min.js:1
v @ girder_lib.min.js:1
u @ girder_lib.min.js:1
d.trigger @ girder_lib.min.js:1
(anonymous) @ girder_lib.min.js:1
l @ girder_lib.min.js:1
fireWith @ girder_lib.min.js:1
n @ girder_lib.min.js:1
(anonymous) @ girder_lib.min.js:1
XMLHttpRequest.send (async)
(anonymous) @ VM254:1
send @ girder_lib.min.js:1
ajax @ girder_lib.min.js:1
S @ girder_lib.min.js:1
fetch @ girder_lib.min.js:1
getAccessLevel @ girder_lib.min.js:1
render @ girder_lib.min.js:1
(anonymous) @ plugin.min.js:1
L @ girder_lib.min.js:1
i @ girder_lib.min.js:1
initialize @ girder_lib.min.js:1
(anonymous) @ plugin.min.js:1
L @ girder_lib.min.js:1
i @ girder_lib.min.js:1
(anonymous) @ plugin.min.js:1
L @ girder_lib.min.js:1
i @ girder_lib.min.js:1
t.View @ girder_lib.min.js:1
constructor @ girder_lib.min.js:1
O.n @ girder_lib.min.js:1
navigateTo @ girder_lib.min.js:1
y @ girder_lib.min.js:1
v @ girder_lib.min.js:1
u @ girder_lib.min.js:1
d.trigger @ girder_lib.min.js:1
(anonymous) @ girder_lib.min.js:1
y @ girder_lib.min.js:1
v @ girder_lib.min.js:1
u @ girder_lib.min.js:1
d.trigger @ girder_lib.min.js:1
(anonymous) @ girder_lib.min.js:1
l @ girder_lib.min.js:1
fireWith @ girder_lib.min.js:1
n @ girder_lib.min.js:1
(anonymous) @ girder_lib.min.js:1
XMLHttpRequest.send (async)
(anonymous) @ VM254:1
send @ girder_lib.min.js:1
ajax @ girder_lib.min.js:1
S @ girder_lib.min.js:1
fetch @ girder_lib.min.js:1
fetchAndInit @ girder_lib.min.js:1
(anonymous) @ girder_lib.min.js:1
execute @ girder_lib.min.js:1
(anonymous) @ girder_lib.min.js:1
(anonymous) @ girder_lib.min.js:1
C.some.C.any @ girder_lib.min.js:1
loadUrl @ girder_lib.min.js:1
navigate @ girder_lib.min.js:1
navigate @ girder_lib.min.js:1
navigate @ girder_lib.min.js:1
_onItemClick @ girder_lib.min.js:1
y @ girder_lib.min.js:1
v @ girder_lib.min.js:1
u @ girder_lib.min.js:1
d.trigger @ girder_lib.min.js:1
click a.g-item-list-link @ girder_lib.min.js:1
dispatch @ girder_lib.min.js:1
m.handle @ girder_lib.min.js:1
girder_lib.min.js:1 500 Internal Server Error {"message": "TypeError: TypeError(\"'NoneType' object has no attribute '__getitem__'\",)", "trace": [["/opt/histomicstk/girder/girder/api/rest.py", 620, "endpointDecorator", "val = fun(self, args, kwargs)"], ["/opt/histomicstk/girder/girder/api/rest.py", 1184, "GET", "return self.handleRoute('GET', path, params)"], ["/opt/histomicstk/girder/girder/api/rest.py", 946, "handleRoute", "val = handler(**kwargs)"], ["/opt/histomicstk/girder/girder/api/rest.py", 437, "wrapped", "return fun(*args, **kwargs)"], ["/opt/histomicstk/girder/plugins/large_image/server/rest/tiles.py", 239, "getTilesInfo", "return self._getTilesInfo(item, params)"], ["/opt/histomicstk/girder/plugins/large_image/server/rest/tiles.py", 197, "_getTilesInfo", "return self.imageItemModel.getMetadata(item, **imageArgs)"], ["/opt/histomicstk/girder/plugins/large_image/server/models/image_item.py", 201, "getMetadata", "tileSource = self._loadTileSource(item, **kwargs)"], ["/opt/histomicstk/girder/plugins/large_image/server/models/image_item.py", 197, "_loadTileSource", "tileSource = AvailableTileSources[sourceName](item, **kwargs)"], ["/opt/histomicstk/girder/plugins/large_image/server/cache_util/cache.py", 181, "__call__", "instance = super(LruCacheMetaclass, cls).__call__(*args, **kwargs)"], ["/opt/histomicstk/girder/plugins/large_image/server/tilesource/pil.py", 106, "__init__", "largeImagePath = self._getLargeImagePath()"], ["/opt/histomicstk/girder/plugins/large_image/server/tilesource/base.py", 1682, "_getLargeImagePath", "assetstore = Assetstore().load(largeImageFile['assetstoreId'])"]], "type": "internal"}

**Comment by manthey** [comment] 2018-01-17 19:48
This is caused by a bug:  When we copy an item that is marked as a large image, the large image information is copied.  Part of this specifies which file is used for the large image,   However, when we copy an item, we copy the files in the item, too.  The reference to the file should be changed to the newly copied file, not the original file.

There are two possible fixes, both of which take some effort:

- We change the references to the new files. 
- When copying an item, the new item could have the large image property removed.  If the automatic rules for making a large_image say that the item should be a large_image, then that code path would reenable it.  However, if the original item has a converted file, we would still have to determine which file this was to prevent copying it to the new item.

Both of these are somewhat tedious to do, since Girder's copy item function creates a new item, saves it, sends a `model.item.copy.prepare` event with the original and new items, copies the files, then sends a `model.item.copy.after` event with just the new item, then reloads the new item and returns it.

Short of adding or changing girder events, the solution would be to handle both the `copy.prepare` and `copy.after` events and save some state.  Rather, we could make a replacement for `copyItem` method for imageItems, but that requires copying a fair amount of functionality from Girder's core method.

**Closed** 2018-01-26 18:33 UTC
